test:
  database: mongoid_config_test
  host: <%= ENV["MONGOID_SPEC_HOST"] %>
  allow_dynamic_fields: false
  include_root_in_json: true
  parameterize_keys: false
  scope_overwrite_exception: false
  persist_in_safe_mode: false
  raise_not_found_error: false
  max_retries_on_connection_failure: 5
  autocreate_indexes: false
  option_no_exist: false
  skip_version_check: false
  logger: false
