test:
  sessions:
    default:
      hosts:
        - <%=ENV["MONGOID_SPEC_HOST"]%>:<%=ENV["MONGOID_SPEC_PORT"]%>
      options:
        consistency: :strong
    replica:
      hosts:
        - localhost:27018
        - localhost:27019
      options:
        consistency: :eventual
        safe: true
  databases:
    default:
      name: mongoid_test
      session: default
    replica:
      name: mongoid_test
      session: replica
  options:
    allow_dynamic_fields: false
    identity_map_enabled: true
    include_root_in_json: true
    include_type_for_serialization: true
    preload_models: true
    scope_overwrite_exception: true
    raise_not_found_error: false
    skip_version_check: false
    use_activesupport_time_zone: false
    use_utc: true
