defaults: &defaults
  hosts: [[localhost, 27017], [localhost, 27017]]
  read_secondary: true
  allow_dynamic_fields: false
  parameterize_keys: false
  persist_in_safe_mode: false
  raise_not_found_error: false
  reconnect_time: 5
  persist_types: false
  option_no_exist: false
  skip_version_check: false

test:
  <<: *defaults
  database: mongoid_config_test
  databases:
    shard_replset:
      hosts: [ [localhost, 27017], [localhost, 27017] ]
      database: multi_db_replset_test
      reconnect_time: 5
