test:
  hosts:
    - - <%= ENV["MONGOID_SPEC_HOST"] %>
      - <%= ENV["MONGOID_SPEC_PORT"] %>
    - - <%= ENV["MONGOID_SPEC_HOST"] %>
      - <%= ENV["MONGOID_SPEC_PORT"] %>
  read: :secondary
  allow_dynamic_fields: false
  parameterize_keys: false
  persist_in_safe_mode: false
  raise_not_found_error: false
  max_retries_on_connection_failure: 5
  option_no_exist: false
  skip_version_check: false
  database: mongoid_config_test
  databases:
    shard_replset:
      hosts:
        - - <%= ENV["MONGOID_SPEC_HOST"] %>
          - <%= ENV["MONGOID_SPEC_PORT"] %>
        - - <%= ENV["MONGOID_SPEC_HOST"] %>
          - <%= ENV["MONGOID_SPEC_PORT"] %>
      database: multi_db_replset_test
      max_retries_on_connection_failure: 5

authenticated:
  hosts:
    - - <%= ENV["MONGOID_SPEC_HOST"] %>
      - <%= ENV["MONGOID_SPEC_PORT"] %>
    - - <%= ENV["MONGOID_SPEC_HOST"] %>
      - <%= ENV["MONGOID_SPEC_PORT"] %>
  read: :secondary
  allow_dynamic_fields: false
  parameterize_keys: false
  persist_in_safe_mode: false
  raise_not_found_error: false
  max_retries_on_connection_failure: 5
  option_no_exist: false
  skip_version_check: false
  database: mongoid_config_authenticated_test
  username: mongoid
  password: test
